server.port=8099
#linux\u6587\u4EF6\u76EE\u5F55
#ftp.downloadDict=/home/hcdq/files/

# windows\u6587\u4EF6\u76EE\u5F55
ftp.downloadDict=D:/jk_project/file/dat/

# \u81EA\u5B9A\u4E49\u9759\u6001\u8D44\u6E90\u76EE\u5F55\uFF0C\u6DFB\u52A0 classpath:/assets/
# \u4FDD\u7559\u539F\u6709\u7684 static \u76EE\u5F55\uFF0C\u7528\u9017\u53F7\u5206\u9694\u591A\u4E2A\u76EE\u5F55
spring.web.resources.static-locations=classpath:/static/,classpath:/assets/